---
title: "data_exploration"
author: "team 4"
date: "2022-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Loading packages
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r, echo=FALSE}
# Load data
all_data <- read_csv("../../data/listings_final.csv")
```


# Data Exploration

```{r all_data}
summary(all_data)
```

```{r}
## Number of room types per city
table(all_data$room_type, all_data$city)
```

```{r}
## Percentage of room types per city
per_city <- table(all_data$city, all_data$room_type)
prop.table(per_city)
```

```{r}
## Percentage of room types total
prop.table(table(all_data$room_type))
```

```{r}
## Number of property types per city
table(all_data$property_type, all_data$city)
```

```{r}
## Percentage of property types per city
prop_city <- table(all_data$city, all_data$property_type)
prop.table(prop_city)
```

```{r}
## Percentage of property types of total
prop.table(table(all_data$property_type))
```

```{r}
## Average number of reviews per city
all_data %>%
  group_by(city) %>%
  summarise_at(vars(number_of_reviews), list(name = mean))
```

```{r}
## Average number of reviews of total
all_data %>%  summarise_at(vars(number_of_reviews), list(name = mean))
```

```{r}
## Average review score per city
all_data %>%
  group_by(city) %>%
  summarise_at(vars(review_scores_rating), list(name = mean))
```

```{r}
## Average review score of total
all_data %>%  summarise_at(vars(review_scores_rating), list(name = mean))
```

```{r}
## Average price per person per city
all_data %>%
  group_by(city) %>%
  summarise_at(vars(price_per_person), list(name = mean))
```

```{r}
## Average price per person of total
all_data %>%  summarise_at(vars(price_per_person), list(name = mean))
```

```{r}
## Number of host is superhost (Superhost=1)
table(all_data$host_is_superhost, all_data$city)
```

```{r}
## Number of host identity verified (Verified=1)
table(all_data$host_is_superhost, all_data$city)
```

# Plotting the data (Bar)

```{r}
# Plot room_type overall
ggplot(all_data, aes(x = room_type)) +
    geom_bar(aes(fill = room_type), position = "dodge") +
    theme(plot.title = element_text(hjust = 0.5)) +
  stat_count(geom = "text", colour = "black", size = 3,
             aes(label = ..count..), position = position_stack(vjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d()
```

```{r}
# Plot room_type per city
ggplot(aes(x = room_type), data = all_data) +
  geom_bar(aes(fill = city), colour = "grey20", lwd = 0.5) +
  labs(y = "property_type_count")
```

```{r}
# Plot property overall
ggplot(all_data, aes(x = property_type)) +
    geom_bar(aes(fill = property_type), position = "dodge") +
    theme(plot.title = element_text(hjust = 0.5)) +
  stat_count(geom = "text", colour = "black", size = 3,
             aes(label = ..count..), position = position_stack(vjust = 1)) +
    labs(x = "Types of property", y = "Number of properties", fill = "Types of property") +
    scale_fill_viridis_d()+
  coord_flip()
```

```{r}
# Plot property per city
ggplot(aes(x = property_type), data = all_data) +
  geom_bar(aes(fill = city), colour = "grey20", lwd = 0.5) +
  labs(y = "property_type_count")+
  coord_flip()
```


# Piecharts

```{r}
# Basic piechart (room type)
piepercent_room<- round(100*table(all_data$room_type)/sum(table(all_data$room_type)), 1)
pie(table(all_data$room_type), labels = piepercent_room, main = "Room pie chart", col = rainbow(length(table(all_data$room_type)), s = 0.5))
legend("topright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(all_data$room_type)), s = 0.5))
```

```{r}
# Basic piechart (property type)
piepercent_prop<- round(100*table(all_data$property_type)/sum(table(all_data$property_type)), 1)
pie(table(all_data$property_type), labels = piepercent_prop, main = "Property pie chart", col = rainbow(length(table(all_data$property_type)), s = 0.6))
legend("topleft", c("Entire condo", "Entire home","Entire loft","Entire rental unit",
                     "Entire serviced apartment","Entire townhouse","Entire villa",
                     "Non-common property type","Private room in condo",
                     "Private room in home","Private room in rental unit",
                     "Room in boutique hotel"), cex = 0.6,
       fill = rainbow(length(table(all_data$property_type)), s = 0.6))
```


